version: '2'
services:
  es:
    build: .
    environment:
        ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
        - ./db:/var/lib/mysql
  kibana:
    image: kibana:5.2
    ports:
      - "5601:5601"
    depends_on:
      - es
